/*
 * esp_lua.c
 *
 * Minimal smoke test confirming that the Lua VM (built by
 * lua_component from the ../lua submodule) runs correctly on the
 * target MCU. This is deliberately scoped to Lua only -- no GPIO,
 * WiFi, or Blockly integration yet. That scope is intentional: this
 * step exists purely to validate the toolchain/build integration
 * before any application logic is layered on top.
 *
 * Target board: ESP32-S3-N16R8 (16 MB flash / 8 MB PSRAM), running on
 * ESP-IDF / FreeRTOS. Set with `idf.py set-target esp32s3` before
 * building.
 *
 * What this test does:
 *   1. Create a fresh Lua state (lua_State).
 *   2. Load the Lua standard library (print, math, string, ...).
 *   3. Execute a small embedded Lua script that computes 10 + 20 and
 *      returns the result.
 *   4. Read the returned integer back into C and log it via ESP_LOG,
 *      alongside any output the script itself printed.
 *   5. Tear down the Lua state.
 *
 * `luaL_dostring()` is the key entry point here: this is exactly
 * where, in a later stage, a Lua script string generated by the
 * Blockly-based web UI (received over HTTP) will be substituted in
 * place of the fixed `kTestScript` constant below.
 */

#include <stdio.h>
#include <stdbool.h>
#include "esp_log.h"

#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"

static const char *TAG = "esp_lua";

/*
 * Fixed test script. `print()` output is routed through Lua's
 * standard I/O library and will appear on stdout (visible in the
 * serial monitor). The script's return value is retrieved separately
 * via the Lua C API below.
 */
static const char *kTestScript =
    "local a = 10\n"
    "local b = 20\n"
    "local sum = a + b\n"
    "print(\"Lua is running on ESP32!\")\n"
    "print(\"Sum of \" .. a .. \" + \" .. b .. \" = \" .. sum)\n"
    "return sum\n";

/*
 * Runs kTestScript to completion and logs the outcome.
 *
 * Returns true if the script executed successfully and produced the
 * expected result, false otherwise. Errors (syntax errors, runtime
 * errors) are logged with the message Lua provides on the stack, then
 * the Lua state is still closed cleanly -- a failing script must never
 * leak the VM or crash the caller.
 */
static bool run_lua_smoke_test(void)
{
    lua_State *L = luaL_newstate();
    if (L == NULL) {
        ESP_LOGE(TAG, "luaL_newstate() failed (out of memory?)");
        return false;
    }

    luaL_openlibs(L);

    /* luaL_dostring() = luaL_loadstring() + lua_pcall(). Returns 0 on
     * success; non-zero means either the script failed to compile
     * (syntax error) or raised a runtime error during execution. */
    int status = luaL_dostring(L, kTestScript);
    if (status != LUA_OK) {
        const char *err_msg = lua_tostring(L, -1);
        ESP_LOGE(TAG, "Lua script failed: %s",
                 err_msg != NULL ? err_msg : "(no error message)");
        lua_pop(L, 1); /* remove error message from the stack */
        lua_close(L);
        return false;
    }

    /* The script's `return sum` leaves one value on the stack. */
    if (!lua_isinteger(L, -1)) {
        ESP_LOGE(TAG, "Unexpected return type from Lua script");
        lua_pop(L, 1);
        lua_close(L);
        return false;
    }

    lua_Integer result = lua_tointeger(L, -1);
    lua_pop(L, 1);

    ESP_LOGI(TAG, "Lua returned to C: %lld", (long long)result);

    lua_close(L);

    return result == 30;
}

void app_main(void)
{
    ESP_LOGI(TAG, "Starting Lua VM smoke test on ESP32-S3-N16R8");

    bool ok = run_lua_smoke_test();

    if (ok) {
        ESP_LOGI(TAG, "Lua VM smoke test PASSED");
    } else {
        ESP_LOGE(TAG, "Lua VM smoke test FAILED");
    }
}